from django.urls import path
from .import views

urlpatterns = [
    path('',views.home,name='home'),
    path('Log_In',views.Log_In,name='Log_In'),
    path('Fun_LogIn',views.Fun_LogIn,name='Fun_LogIn'),
    path('adminHome',views.adminHome,name='adminHome'),
    path('categories',views.categories,name='categories'),
    path('add_categories',views.add_categories,name='add_categories'),
    path('products',views.products,name='products'),
    path('add_products',views.add_products,name='add_products'),
    path('view_products',views.view_products,name='view_products'),
    path('edit_prdt/<int:pd>',views.edit_prdt,name='edit_prdt'),
    path('edit_products/<int:pd>',views.edit_products,name='edit_products'),
    path('delete_product/<int:pd>',views.delete_product,name='delete_product'),
    path('Log_Out',views.Log_Out,name='Log_Out'),
    path('Sign_Up',views.Sign_Up,name='Sign_Up'),
    path('Fun_Signup',views.Fun_Signup,name='Fun_Signup'),
    path('view_users',views.view_users,name='view_users'),
    path('delete_user/<int:ud>',views.delete_user,name='delete_user'),
    path('userHome',views.userHome,name='userHome'),
    # path('Gold',views.Gold,name='Gold'),
    # path('Diamonds',views.Diamonds,name='Diamonds'),
    # path('Platinum',views.Platinum,name='Platinum'),
    # path('Silver',views.Silver,name='Silver'),
    path('user_profile',views.user_profile,name='user_profile'),
    path('edit_prf',views.edit_prf,name='edit_prf'),
    path('edit_profile',views.edit_profile,name='edit_profile'),
    path('Cart_page',views.Cart_page,name='Cart_page'),
    path('addto_cart/<int:pd>',views.addto_cart,name='addto_cart'),
    path('Increase_quantity/<int:qd>',views.Increase_quantity,name='Increase_quantity'),
    path('Decrease_quantity/<int:qd>',views.Decrease_quantity,name='Decrease_quantity'),
    path('deletecart_item/<int:cd>',views.deletecart_item,name='deletecart_item'),
    path('Place_Order',views.Place_Order,name='Place_Order'),
    path('modal_closeBtn',views.modal_closeBtn,name='modal_closeBtn'),
    path('store',views.store,name='store'),
    path('contact_us',views.contact_us,name='contact_us'),
    path('all-collections/<str:category_name>/', views.AllCollections, name='AllCollections'),

]